version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /control-plane
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /controllers
    schedule:
      interval: weekly
    groups:
      k8s-stack:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
    ignore:
      - dependency-name: "k8s.io/*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: gomod
    directory: /providers
    schedule:
      interval: weekly
    groups:
      k8s-stack:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
    ignore:
      - dependency-name: "k8s.io/*"
        update-types:
          - version-update:semver-major
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types:
          - version-update:semver-major
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
