#!/usr/bin/env bash
# Build platform module images, push to the local registry and emit a Helm
# values file pinning every image by sha256 digest (R3 digest-only policy).
set -euo pipefail

REGISTRY="${REGISTRY:-localhost:5000}"
MODULES=(control-plane controllers)
OUT="deploy/helm/build-digests.yaml"

key_for() {
  case "$1" in
    control-plane) echo "controlPlane" ;;
    *) echo "$1" | tr - _ ;;
  esac
}

{
  echo "# Generated by scripts/build-images.sh — do not edit."
} > "$OUT"

for mod in "${MODULES[@]}"; do
  tag="$REGISTRY/tenara/$mod:local"
  docker build -q --build-arg MODULE="$mod" -t "$tag" .
  docker push "$tag" >/dev/null
  digest="$(docker inspect --format '{{index .RepoDigests 0}}' "$tag" | sed "s|^.*@||")"
  case "$digest" in
    sha256:[0-9a-f]*) ;;
    *) echo "FATAL: no valid digest for $mod ($digest)" >&2; exit 1 ;;
  esac
  echo "$(key_for "$mod"): {digest: $digest}" >> "$OUT"
  echo "pushed $mod -> $digest"
done

echo "wrote $OUT"
